apiVersion: extensions/v1beta1
kind: Deployment 
# 资源类型1 Deployment
# 资源类型2 DaemonSet 每个Node最多只能运行一个副本 （日志收集、Prometheus ）
metadata: #元数据
  name: nginx-deployment
spec: #Deployment规格
  replicas: 1
  template:
    metadata:  #pod的元数据
      labels:
        app: web_server
    spec: #pod规格
      containers:
      - name: nginx
        image: nginx:1.7.9
      #nodeSelector: #lable 指定部署至disktype=ssd的node上
      #  disktype: ssd
# 执行命令 kubectl apply -f nginx.yml