apiVersion: v1
kind: Service
metadata: 
  name: httpd-svc
spec:
  # type: NodePort
  type: LoadBalancer
  selector: # 挑选label 为run, httpd的Pod作为Service的后端
    run: httpd
  ports: # 映射端口
  - protocol: TCP
    # nodePort: 30000 # 节点监听接口
    port: 8080
    targetPort: 80 # 目标端口